### ISSUE TITLE
LTS Version 1.31 support?

### ISSUE THREAD

**Issue by GeraldST** [SemanticMediaWiki/SemanticBundle#11]
I tried to install Semantic Bundle Version 3.1.0 on MediaWiki Core LTS-Version 1.31.6 but got an error running the update.php which broke the site:

PHP Fatal error:  Uncaught ExtensionDependencyError: Mermaid is not compatible with the current MediaWiki core (version 1.31.6), it requires: >= 1.33.
 in /home/infopedia/mediawiki/includes/registration/ExtensionRegistry.php:278

To me it seems that Mermaid has dropped support for 1.31 already a year ago - Semantic Bundle says it would run on 1.31+. Which is obviously not true for me ...

**Comment by akuckartz** [comment]
https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/570 has relevant information.

**Comment by kghbln** [comment]
@GeraldST Thanks for reporting. I have authored a change to regain support for MW 1.31.x You can change your local file accordingly to move on until the fix was merged and a new release of the bundle was done.

**Comment by GeraldST** [comment]
Thank you - I saw that you changed it to require Mermaid 2.1.0 - are you sure that this version works with MW 1.31? It does say differently in the [Release Notes](https://github.com/SemanticMediaWiki/Mermaid/blob/master/docs/RELEASE-NOTES.md#210). IMHO according to the release notes the last version supporting it would be 2.0.0.

**Comment by kghbln** [comment]
@GeraldST Ah, correct. Good catch. Thanks. What a mess. However with 2.1.0 at least MW would at least longer have complained.

**Comment by JeroenDeDauw** [comment]
The fallout of mediawiki.api.parse continues... volcanic winter basically.

**Comment by JeroenDeDauw** [comment]
This should be fixed with the 3.1.2 release that I just made.
