### ISSUE TITLE
Possible bug related to Semantic Glossary

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticBundle#22]
https://sourceforge.net/p/semediawiki/mailman/message/37139074/

**Comment by kghbln** [comment]
Semantic Glossary is no longer compatible with MW 1.35

**Comment by JeroenDeDauw** [comment]
Fix: drop SG and release SB 4.0

**Comment by kghbln** [comment]
In a way this not exactly what I had in mind but for the time being it appears to be the solution to go for.

**Comment by kghbln** [comment]
#24 to not forget to add it again
