### ISSUE TITLE
Add Semantic Glossary to the bundle

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticBundle#24]
With https://github.com/ProfessionalWiki/SemanticBundle/issues/22 we had to remove Semantic Glossary from the bundle. Once Semantic Glossary is compatible again with MediaWiki 1.35 it should be added again.

**Comment by lotusccong** [comment]
Semantic Glossary already released 4.0.0 on 2021-7-09 that compatible with MediaWiki 1.35 and Semantic MediaWiki 3.1

**Comment by kghbln** [comment]
Will probably never happen. SG is unstable for over a year now. Thus closing.
