### ISSUE TITLE
composer error in installation

### ISSUE THREAD

**Issue by bescheid** [SemanticMediaWiki/SemanticBundle#31]

**Comment by bescheid** [comment]
my composer.local.json has  

`{
	"require": {
                "mediawiki/semantic-media-wiki": "~4.0",
		"mediawiki/semantic-bundle": "~4.0"
        },
	"config": {
		"allow-plugins": {
			"composer/installers": true,
			"wikimedia/composer-merge-plugin": true
		}
	}
}
`
but when I try to update
`php composer.phar update mediawiki/semantic-bundle --no-dev -o`

i get an error notice complaining about lowercase: 

![composer error screenshot](https://user-images.githubusercontent.com/49399847/158021147-7c56828b-e9ce-4dcc-838c-0c409be4594e.png)

**Comment by JeroenDeDauw** [comment]
Your Composer version is too new for your MediaWiki version. This has nothing to do with Semantic Bundle.

Either get the latest patch version of MediaWiki (I know it is fixed on 1.35.x and above) or downgrade composer (I am not sure how far).

**Comment by bescheid** [comment]
I am presently testing a new installation of MW 1.37.1 :( but it seems to work with Composer 2.1.0, thank you!
