### ISSUE TITLE
Support PHP 8.x

### ISSUE THREAD

**Issue by streiml** [SemanticMediaWiki/SemanticBundle#37]
Hello,

when will be Mediawiki 1.39.x and PHP 8.x supported?

**Comment by JeroenDeDauw** [comment]
PHP 8.x should already be supported, to the degree that SMW itself supports it. SMW supports PHP 8.0 but the latest release does not yet support PHP 8.1. Same goes for MediaWiki. Latest SMW does not yet fully support MediaWiki 1.39. Both of those are in the works for the next SMW release though.

**Comment by streiml** [comment]
Thanks for your reply. Do you have any idea how long it would take to support MediaWiki 1.39.x?

**Comment by JeroenDeDauw** [comment]
A month or so, probably

**Comment by streiml** [comment]
Thanks!
