### ISSUE TITLE
Regarding Packagist 6.0.1 versus 6.1

### ISSUE THREAD

**Issue by Kimse84** [SemanticMediaWiki/SemanticBundle#41]
Let me first and foremost say it is a great extension to the SMV and Mediawiki.

I have tried to install 6.1 but get a composer error. It simply says 6.1 isn't there. I checked with Packagist and it says 6.0.1 as the newest omitting the dev install.

Hope anyone can shed some light. :)

**Comment by kghbln** [comment]
Packagist is auto-updating information from this repo, but I am unsure which intervals. Since the last update was on 2024-07-10 and the release was made after that date ... Anyhow, I just triggered the update manually, and now the info on Packagist is current.

**Comment by Kimse84** [comment]
You are a hero :D thank you so much and thank you for your work :)
