### ISSUE TITLE
Does Semantic Bundle show on Special:Version?

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticBundle#5]
I do not think it does. However I believe this will be a good idea. If the bundle registers like a regular extension we could track it's usage.

**Comment by JeroenDeDauw** [comment]
Uh I just uninstalled it so can't show you screenshot.

It does show up there. Below the MW and PHP versions.

**Comment by kghbln** [comment]
> It does show up there. Below the MW and PHP versions.

This would still be different to a regular extension? Can this be explored via the API? Probably WikiApiary needs to be adapted to track this. Not sure.

**Comment by JeroenDeDauw** [comment]
I guess not via the API

**Comment by kghbln** [comment]
> I guess not via the API

In this case we have no chance to easily detect its usage. Can this one be turned into a regular extension, meaning using extension credits or what it is called in extension registration times.

**Comment by JeroenDeDauw** [comment]
Latest release shows up as extension on special:version due to https://github.com/SemanticMediaWiki/SemanticBundle/blob/master/SemanticBundle.php#L26

**Comment by JeroenDeDauw** [comment]
Rant: MW does not allow to order extensions on special:version any more. This is derp. It makes sense to have the bundle on top and to also have SMW on top. Not ModernTimeline or some other rando SMW extension.

**Comment by kghbln** [comment]
Thanks a lot. I was not aware that it was ever possible to have a specific order on Special:Version. I guess it is ok like it is now since the important thing is that you can track its existence.
