### ISSUE TITLE
SMW loading problems

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticBundle#9]
https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/4190#issuecomment-546708092

Might be fixed by removing the call, though maybe this causes issues with loading SMW extensions before enableSemantics() is called.

Might also not be relevant after https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/4190

**Comment by JeroenDeDauw** [comment]
Ping @mwjames

**Comment by kghbln** [comment]
Yes, indeed SMW is not loaded by `wtfLoadExtensions` I wonder why this did not pop up earlier. Step 4 should happen prior to step 3 and no need to call SMW in "SemanticBundle.php"
